config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :comments
  resources :shops
  use_doorkeeper
  resources :products
  resources :orders
  resources :shops
  mount ApplicationAPI, at: 'api'

  root 'products#index'
  
  devise_for :user, controllers: { sessions: "users/sessions",
                                   registrations: "users/registrations",
                                   invitations: "users/invitations",
                                   confirmations: "users/confirmations",
                                   omniauth_callbacks: 'users/omniauth_callbacks',
                                   passwords: "users/passwords"
                                  } 
  devise_scope :user do
    get 'users/new_by_mobile', :to => 'users/registrations#new_by_mobile'
    post 'users/send_sms', :to => 'users/registrations#send_sms'
    post 'users/sms_verify', :to => 'users/registrations#sms_verify'
    get 'users/bind', :to => 'users/registrations#bind'
    post 'users/create_bind', :to => 'users/registrations#create_bind'
  end

  resources :users do 
    resources :orders
  end

  get 'attachments/:id/downloadfile' => 'attachments#downloadfile', as: :downloadfile
  get 'attachments/:id/downloadfile/:type' => 'attachments#downloadfile', as: :downloadfile_type

  match '/user/auth/wechat' => 'users/omniauth_callbacks#passthru', via: [:get, :post]
  match '/user/auth/wechat/callback' => 'users/omniauth_callbacks#wechat', via: [:get, :post]

end

app/models/shop.rb
class Shop < ActiveRecord::Base
	belongs_to :user
	has_many :products
	has_many :orders
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  after_action :clear_caches, only: [:create, :update, :destroy]
  caches_action :index, cache_path: Proc.new { {cache_id: current_user.id } }

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
       params.require(:shop).permit(:name, :status, :user_id)
    end

    def clear_caches
      p "-------------------clear #{current_user.show_name}'s cache----------------------- "
      expire_action(controller: 'shops', action: 'index', cache_id: current_user.id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for @shop, :html => { :class => "form-horizontal shop" } do |f| %>

  <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label '名称', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label '状态', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label '店主', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

   <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit '更新', :class => 'btn btn-primary' %>
      <%= link_to '取消',
                shops_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/shops/edit.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "编辑商铺"} do |box| %>
	<% case box when Box::Body %>
</div>
<%= render :partial => 'form' %>
	<% end %>
<% end %>

app/views/shops/index.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "店铺列表"} do |box| %>
 <div class="col-md-12">
 <% case box when Box::Body %>
<%- model_class = Shop -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th>名称</th>
      <th>状态</th>
      <th>店主</th>
      <th>创建时间</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.name, shop_path(shop) %></td>
        <td><%= shop.status %></td>
        <td><%= shop.user_id %></td>
        <td><%= shop.created_at %></td>
        <td>
          <%= link_to '编辑', edit_shop_path(shop), :class => 'btn btn-default btn-xs' %>
          <%= link_to '删除',
                      shop_path(shop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '创建店铺(实际场景应该用户走一个店铺申请审核通过后产生)',
            new_shop_path,
            :class => 'btn btn-primary' %>
<% end %>
</div>
<% end %>

app/views/shops/new.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "添加店铺(实际不允许)"} do |box| %>
	<% case box when Box::Body %>
<%= render :partial => 'form' %>
 <% end %>
<% end %>

app/views/shops/show.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "商品查看"} do |box| %>
<% case box when Box::Body %>
<dl class="dl-horizontal">
  <dt><strong>名称:</strong></dt>
  <dd><%= @shop.name %></dd>
  <dt><strong>状态:</strong></dt>
  <dd><%= @shop.status %></dd>
  <dt><strong>店主:</strong></dt>
  <dd><%= @shop.user_id %></dd>
</dl>

<%= link_to '返回',
              shops_path, :class => 'btn btn-default'  %>
<%= link_to '编辑',
              edit_shop_path(@shop), :class => 'btn btn-default' %>
<%= link_to '删除',
              shop_path(@shop),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
              <% end %>
<% end %>