config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :comments
  resources :shops
  use_doorkeeper
  resources :products
  resources :orders
  resources :shops
  mount ApplicationAPI, at: 'api'

  root 'products#index'
  
  devise_for :user, controllers: { sessions: "users/sessions",
                                   registrations: "users/registrations",
                                   invitations: "users/invitations",
                                   confirmations: "users/confirmations",
                                   omniauth_callbacks: 'users/omniauth_callbacks',
                                   passwords: "users/passwords"
                                  } 
  devise_scope :user do
    get 'users/new_by_mobile', :to => 'users/registrations#new_by_mobile'
    post 'users/send_sms', :to => 'users/registrations#send_sms'
    post 'users/sms_verify', :to => 'users/registrations#sms_verify'
    get 'users/bind', :to => 'users/registrations#bind'
    post 'users/create_bind', :to => 'users/registrations#create_bind'
  end

  resources :users do 
    resources :orders
  end

  get 'attachments/:id/downloadfile' => 'attachments#downloadfile', as: :downloadfile
  get 'attachments/:id/downloadfile/:type' => 'attachments#downloadfile', as: :downloadfile_type

  match '/user/auth/wechat' => 'users/omniauth_callbacks#passthru', via: [:get, :post]
  match '/user/auth/wechat/callback' => 'users/omniauth_callbacks#wechat', via: [:get, :post]

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  # resourcify
  belongs_to :account
  belongs_to :user
  belongs_to :product,touch: true,counter_cache: true
  belongs_to :shop, touch: true
  has_many :comments

  mount_uploader :file_name_uid, AttachmentUploader

  attr_accessor :rotate
  after_save :rotate_image, if: ->(obj){ obj.rotate.present? } #and obj.rotate? }

  def rotate_image
    self.file_name_uid.recreate_versions!
  end

  def get_originalfile
     file_name_uid.get_originalfile
  end

  def get_filesize
     file_name_uid.get_filesize
  end

  def show_attaimg_paths
    suffix = file_name_uid.to_s.rindex(".")
    atType = file_name_uid.to_s[suffix.to_i+1,file_name_uid.to_s.length]
    imgPath = ""
    simgPath = ""
    showPath = false
    paths = Array.new
    case atType.to_s.downcase
      when "jpg","gif","bmp","jpeg","png"
        imgPath = "/attachments/#{id}/downloadfile"
        simgPath = "/attachments/#{id}/downloadfile/normal"
        showPath = true
      when "ppt","pptx"
        simgPath= imgPath = "icon-ppt.png"
      when "rar"
        simgPath= imgPath = "icon-rar.png"
      when "zip"
        simgPath= imgPath = "icon-zip.png"
      when "pdf"
        simgPath= imgPath = "icon-pdf.png"
      when "doc","odt"
        simgPath= imgPath = "icon-word.png"
      when "xls","ods"
        simgPath= imgPath = "icon-xls.png"
      when "txt"
        simgPath= imgPath = "icon-txt.png"
      when "avi"
        simgPath= imgPath = "icon-avi.png"
      when "css"
        simgPath= imgPath = "icon-css.png"
      when "csv"
        simgPath= imgPath = "icon-csv.png"
      when "dmg"
        simgPath= imgPath = "icon-dmg.png"
      when "docx"
        simgPath= imgPath = "icon-docx.png"
      when "dwg"
        simgPath= imgPath = "icon-dwg.png"
      when "exe"
        simgPath= imgPath = "icon-exe.png"
      when "html"
        simgPath= imgPath = "icon-html.png"
      when "iso"
        simgPath= imgPath = "icon-iso.png"
      when "jar"
        simgPath= imgPath = "icon-jar.png"
      when "java"
        simgPath= imgPath ="icon-java.png"
      when "js"
        simgPath= imgPath = "icon-js.png"
      when "jsp"
        simgPath= imgPath = "icon-jsp.png"
      when "key"
        simgPath= imgPath = "icon-key.png"
      when "mov"
        simgPath= imgPath = "icon-mov.png"
      when "mp3"
        simgPath= imgPath = "icon-mp3.png"
      when "mp4"
        simgPath= imgPath = "icon-mp4.png"
      when "pkg"
        simgPath= imgPath = "icon-pkg.png"
      when "pps"
        simgPath= imgPath = "icon-pps.png"
      when "psd"
        simgPath= imgPath = "icon-psd.png"
      when "rb"
        simgPath= imgPath = "icon-rb.png"
      when "rm"
        simgPath= imgPath = "icon-rm.png"
      when "wav"
        simgPath= imgPath = "icon-wav.png"
      when "xlsx"
        simgPath= imgPath = "icon-xlsx.png"
      when "xml"
        simgPath= imgPath = "icon-xml.png"
      when "yml"
        simgPath= imgPath = "icon-yml.png"
      when "conf"
        simgPath= imgPath = "icon-conf.png"
      when "ini"
        simgPath= imgPath ="icon-ini.png"
      else
        simgPath= imgPath = "icon-nothing.png"
    end
    paths[0] = imgPath
    paths[1] = simgPath
    paths[2] = showPath
    return paths
  end

  def display_name
    self.file_name
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json

  def create
    @attachment = Attachment.new(attachment_params)
    product_id = params[:product_id]
    @attachment.product_id = product_id  unless product_id.blank?
    @attachment.tap do |x|
      x.user_id = params[:user_id],
      x.file_type = params[:file_type]
    end if params[:uploadtype].eql?('bst')
    @attachment.file_name=@attachment.get_originalfile.file_name
    p "params:#{params.to_s}"
    @attachment.rotate = true
    # respond_to do |format|
    path = params[:submittype] == "remote" ? @attachment : "/products/#{product_id}"
    respond_to do |format|
      if @attachment.save
        @attachment.update(file_size: @attachment.get_filesize)
        format.html{ redirect_to path, notice: '上传成功.' }
      else
        format.html{ redirect_to path, notice: '上传成功.' }  
      end
    end
    
  end




  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def downloadfile
    p "Downloading file ".center(50,'-')
    begin
      atta = Attachment.find(params[:id])
    rescue => e
      atta = Attachment.find(params[:id])
    end
    type = params[:type]
    path = atta.file_name_uid_url
    unless type.nil?
      if type == "large"
        path = atta.file_name_uid_url(:large)
      elsif type == "normal"
        path = atta.file_name_uid_url(:normal)
      elsif type == "small48"
        path = atta.file_name_uid_url(:small48)
      elsif type == "small32"
        path = atta.file_name_uid_url(:small32)
      elsif type == "small24"
        path = atta.file_name_uid_url(:small24)
      elsif type == "big"
        path = atta.file_name_uid_url(:big)
      else
        path = atta.file_name_uid_url(type.to_sym)
      end
    end

    # end
    begin
      if authorize_user 
        response.headers['X-Accel-Redirect'] = path
        response.headers['Content-Type'] = "application/octet-stream"
        response.headers['Content-Dispostion'] = "attachment;filename="+path
        render :nothing => true
        send_file(Rails.root.join(path).to_s, filename: atta.file_name, dispostion: "inline", status: 200, stream: true, x_sendfile: true )
      else
        redirect_to product_path(atta.product_id),notice: '下载失败!!!'
        # render :file => "#{Rails.root.to_s}/public/404.html"
      end
    rescue =>e
      p e.message
    end
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    def authorize_user
      User.select(:id).map{|x| x.id}.include?(current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:file_name,:file_name_uid, :file_size,:file_type, :version, :product_id, :comment_id, :shop_id, :user_id)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
  #attachment:附件本身
  #tagtype: 'link'=图片所略图和弹出预览,'download'=图片缩略图和下载,'image'=只展示图片
  def image_attach_to(attachment, tagtype='image', html_options ={})
    paths = attachment.show_attaimg_paths
    imgPath = paths[0] #原图
    simgPath = paths[1] #缩略图
    showPath = paths[2] #是否支持弹出原图(仅图片格式支持)
    if 'link'.eql?(tagtype)
      link_to(image_tag(simgPath,html_options),downloadfile_path(attachment),class: "lightbox",rel: "lightbox",title: attachment.file_name)
    elsif 'download'.eql?(tagtype)
      link_to(image_tag(simgPath,html_options),downloadfile_path(attachment),class: "color_green_0")
    elsif 'show'.eql?(tagtype)
      link_to(image_tag(imgPath,html_options),downloadfile_path(attachment),class: "lightbox",rel: "lightbox",title: attachment.file_name)
    elsif 'image'.eql?(tagtype)
      if showPath
        image_tag(simgPath,html_options)
      else
        image_tag(imgPath,html_options)
      end
    end
  end

end

app/views/attachments/_attachment.html.erb
<%
   paths = atta.show_attaimg_paths
   imgPath = paths[0]
   simgPath = paths[1]
   showPath = paths[2]

%>
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 new-task-file-img-padding-5" id="attachments_<%= atta.id %>">
  <div class="new-file-img-box">
    <div class="new-file-box-img">
      <% if showPath %>
          <%= image_attach_to(atta, "link") %>
      <% else
      %>
          <%= image_attach_to(atta, "image") %>
      <%
         end
      %>
    </div>
    <div class="new-file-box-information clearfix">
      <div class="new-file-box-information-title">
        <a href="#" title="<%= atta.file_name %>"><%= atta.file_name %></a>
      </div>
      <div class="new-file-box-information-size">
        <div class="new-file-box-information-size-size">
          <p><%= number_to_human_size atta.file_size %></p>
        </div>
      </div>
      <div class="new-file-box-information-tool">
        <div class="new-file-box-information-item" data-attach-operate="<%= atta.id %>">
          <a href="javascript:void(0);">
            <%= image_tag "hide-icon-hui.png" %>
          </a>
        </div>
        <div class="new-file-box-information-hide" style="display:none;" id="atta_operate_<%= atta.id %>">
          <div class="new-file-box-information-item">
            <%= link_to(image_tag("download-icon-black.png", alt: "",title: "下载"), downloadfile_path(atta), type: "no-loading") %>
          </div>
          <div class="new-file-box-information-item">
            <%
               #if atta.user_id == current_user.id || current_user.id == @project.user.id
               if can? :destroy, atta
            %>
                <div class="new-file-box-information-item">
                  <%= link_to(image_tag("delete-icon-black.png", alt: "",title: "删除"), nil, {href: "javascript:void(0)", onclick: "deleteObjData('attachments','#{atta.id}','#{@task.id}')", type: "no-loading"}) %>
                </div>
            <%
               end
            %>
          </div>
          <div class="new-file-box-information-item-right">
            <%= link_to("/attachments/#{atta.try(:id)}", "data-toggle" => 'popover', role: "button", title: "评论", "data-html" => true, "data-content" => '', template: '<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>', remote: true, onclick: "prePopover(this)") do %>
                <%= image_tag "chat-icon-black.png", alt: "" %>
                <span>(<c id="attach_comments_count_<%= atta.id %>"><%= atta.comments_count.nil? ? 0 : atta.comments_count %></c>)</span>
            <% end %>
            </a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attachments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>