config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :comments
  resources :shops
  use_doorkeeper
  resources :products
  resources :orders
  resources :shops
  mount ApplicationAPI, at: 'api'

  root 'products#index'
  
  devise_for :user, controllers: { sessions: "users/sessions",
                                   registrations: "users/registrations",
                                   invitations: "users/invitations",
                                   confirmations: "users/confirmations",
                                   omniauth_callbacks: 'users/omniauth_callbacks',
                                   passwords: "users/passwords"
                                  } 
  devise_scope :user do
    get 'users/new_by_mobile', :to => 'users/registrations#new_by_mobile'
    post 'users/send_sms', :to => 'users/registrations#send_sms'
    post 'users/sms_verify', :to => 'users/registrations#sms_verify'
    get 'users/bind', :to => 'users/registrations#bind'
    post 'users/create_bind', :to => 'users/registrations#create_bind'
  end

  resources :users do 
    resources :orders
  end

  get 'attachments/:id/downloadfile' => 'attachments#downloadfile', as: :downloadfile
  get 'attachments/:id/downloadfile/:type' => 'attachments#downloadfile', as: :downloadfile_type

  match '/user/auth/wechat' => 'users/omniauth_callbacks#passthru', via: [:get, :post]
  match '/user/auth/wechat/callback' => 'users/omniauth_callbacks#wechat', via: [:get, :post]

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :shop
	belongs_to :order

    has_many :attachments
	# PRODUCT_ALL_CACHE = "product_all"
	# def search
	#     products = Rails.cache.exist?(PRODUCT_ALL_CACHE) ? Rails.cache.read(PRODUCT_ALL_CACHE) : Product.all
	#     Rails.cache.write(PRODUCT_ALL_CACHE, products)
	#     products
	# end

	def all_attachments
	    # task_attachments_all = []
	    task_attachments = self.attachments.order(created_at: :desc)
	    # task_attachments.each do |atta|
	    #   attach_h = {:attachment => atta}
	    #   task_attachments_all.push attach_h
	    # end
	 	
        task_attachments_all = [].tap do |x|
        	task_attachments.each { |atta| x << {attachment: atta} }
        end
	    task_attachments_all
  	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  after_action :clear_caches, only: [:create, :update, :destroy]
  caches_action :index, cache_path: Proc.new { |cache_id| {cache_id: current_user.id }}
  # caches_action :index, expires_in: 1.hour
  # GET /products
  # GET /products.json
  def index
    # product = Product.new
    # @products = product.search
    @products =  Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
     @product_attachments = @product.all_attachments
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create 
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :sprice, :desc)
    end

    def clear_caches
      p "-------------------clear #{current_user.show_name}'s cache----------------------- "
      expire_action(controller: 'products', action: 'index', cache_id: current_user.id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_attachment.html.erb
<%
   paths = atta.show_attaimg_paths
   imgPath = paths[0]
   simgPath = paths[1]
   showPath = paths[2]

%>
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 new-task-file-img-padding-5" id="attachments_<%= atta.id %>">
  <div class="new-file-img-box">
    <div class="new-file-box-img">
      <% if showPath %>
          <%= image_attach_to(atta, "link") %>
      <% else
      %>
          <%= image_attach_to(atta, "image") %>
      <%
         end
      %>
    </div>
    <div class="new-file-box-information clearfix">
      <div class="new-file-box-information-title">
        <a href="#" title="<%= atta.file_name %>"><%= atta.file_name %></a>
      </div>
      <div class="new-file-box-information-size">
        <div class="new-file-box-information-size-size">
          <p><%= number_to_human_size atta.file_size %></p>
        </div>
      </div>
      <div class="new-file-box-information-tool">
        <div class="new-file-box-information-item" data-attach-operate="<%= atta.id %>">
          <a href="javascript:void(0);">
            <%= image_tag "hide-icon-hui.png" %>
          </a>
        </div>
        <div class="new-file-box-information-hide" style="display:none;" id="atta_operate_<%= atta.id %>">
          <div class="new-file-box-information-item">
            <%= link_to(image_tag("download-icon-black.png", alt: "",title: "下载"), downloadfile_path(atta), type: "no-loading") %>
          </div>
          <div class="new-file-box-information-item">
    
                <div class="new-file-box-information-item">
                  <%= link_to(image_tag("delete-icon-black.png", alt: "",title: "删除"), nil, {href: "javascript:void(0)", onclick: "deleteObjData('attachments','#{atta.id}','#{@product.id}')", type: "no-loading"}) %>
                </div>
        
          </div>
         
        </div>

      </div>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label '名称', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label '价格', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sprice, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sprice) %>
  </div>
  <div class="form-group">
    <%= f.label '描述', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :desc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:desc) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit '更新', :class => 'btn btn-primary' %>
      <%= link_to '取消',
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/_pop_file_input.html.erb
<div id="fileinput_bs" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridModalLabel" aria-hidden="true">
  <div class="modal-dialog-fileinput-bs">
    <div class="modal-content">
      <div class="modal-header color-black-5">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title color-white-2" id="gridModalLabel">商品图片列表</h4>
      </div>
      <form enctype="multipart/form-data">
        <div class="form-group">
          <input id="file-5" class="file" type="file" name="attachment[file_name_uid]" multiple data-preview-file-type="any" data-upload-url="/attachments?product_id=<%= @product.id %>&user_id=<%= current_user.id %>&file_type=attachment&uploadtype=bst">
        </div>
      </form>
    </div>
  </div>
  <script>
    //暂不调试
    // $(document).ready(function () {
    //   $(".form-group").children("div:first-child").attr("class", "file-input-ajax-new");

    //   $('#file-5').on('fileuploaded', function (event, data, previewId, index) {
    //     var form = data.form, files = data.files, extra = data.extra,
    //         response = data.response, reader = data.reader;
    //     progress = $('.kv-upload-progress .progress-bar').attr('aria-valuenow')
    //     if (progress == "100") {
    //       appendNotice("上传成功!");
    //       window.location.reload();
    //     }
    //   });
    // });
  </script>
</div>

app/views/products/edit.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "编辑商品"} do |box| %>
	<% case box when Box::Body %>
</div>
<%= render :partial => 'form' %>
	<% end %>
<% end %>

app/views/products/index.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "商品列表"} do |box| %>
 <div class="col-md-12">
 <% case box when Box::Body %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>名称</th>
      <th>价格</th>
      <th>描述</th>
      <th>时间</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= product.sprice %></td>
        <td><%= product.desc %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to '编辑', edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to '删除',
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '创建商品(实际场景应该是在商铺平台添加)',
            new_product_path,
            :class => 'btn btn-primary' %>

            <% end %>
            </div>
<% end %>

app/views/products/new.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "添加商品"} do |box| %>
	<% case box when Box::Body %>
<%= render :partial => 'form' %>
 <% end %>
<% end %>

app/views/products/show.html.erb
<%= render layout: 'shared/default_box', locals: { box_title: "商品查看"} do |box| %>
<% case box when Box::Body %>
<%= render "pop_file_input" %>
<dl class="dl-horizontal">
  <dt><strong>名称:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong>价格:</strong></dt>
  <dd><%= @product.sprice %></dd>
  <dt><strong>描述:</strong></dt>
  <dd><%= @product.desc %></dd>

  <dt><strong>商品图片:</strong></dt>
  <dd>
    <button type="button" class="btn btn-default"  data-toggle="modal" data-target="#fileinput_bs" type="button">
          <%= image_tag "upload-icon-green.png", alt: "" %>
    </button>
  </dd>
  <dt>
    <% @attachment = Attachment.new %>
        <%= form_for @attachment, html: {id: "product_attachment_new", enctype: "multipart/form-data"} do |f| %>
            <input type="file" style="display:none;" id="product_attach_file_name_uid" data-obj-name="product" name="attachment[file_name_uid]">
            <input type="hidden" id="attachment_file_name_uid_cache" name="attachment[file_name_uid_cache]">
            <%= hidden_field 'attachment', 'user_id', value: current_user.id %>
            <%= hidden_field 'attachment', 'product_id', value: @product.id %>
        <% end %>
        <div class="new-file-content">
          <div class="row" id="products_attachments_div">
            <!--  loop attachment -->
          </div>
        </div>
  </dt>
   

</dl>

<div class="new-file-content">
              <div class="row" id="projects_attachments_div">

                <%
                   @product_attachments.each do |atta|
                      atta.each do |key,value| %>
                      <%= render "attachment", atta: value %>
                  <% end
                 end%>
              </div>
            </div>
 

<%= link_to '返回',
              products_path, :class => 'btn btn-default'  %>
<%= link_to '编辑',
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to '删除',
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
              <% end %>
<% end %>